version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - main
configuration: Release
platform: Any CPU
clone_depth: 1
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- cmd: dotnet restore
build:
  project: Logzio.NLog.Extension.sln
  verbosity: minimal
after_test:
- cmd: dotnet pack src\Logzio.NLog.Extensions\ -c Release
deploy:
- provider: NuGet
  api_key:
    secure: pS/lyHg6LcDkR995HR5EUxEgF4W8124Zl6vmBZSJJurU/mPxPTSYms9wBXzNp5FP
  skip_symbols: false
  artifact: /.*(\.|\.s)nupkg/
  on:
    branch: main
