version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - main
configuration: Release
platform: Any CPU
clone_depth: 1
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true
before_build:
- cmd: dotnet restore Logzio.NLog.Extension.sln
build:
  project: Logzio.NLog.Extension.sln
  publish_nuget: true
  verbosity: minimal
after_test:
- cmd: dotnet pack src\Logzio.NLog.Extensions\ -c Release
artifacts:
- path: '*.nupkg'
  name: LogzioNLogExtensions
deploy:
- provider: NuGet
  api_key:
    secure: pS/lyHg6LcDkR995HR5EUxEgF4W8124Zl6vmBZSJJurU/mPxPTSYms9wBXzNp5FP
  skip_symbols: false
  artifact: LogzioNLogExtensions
  on:
    branch: main