version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - main
configuration: Release
platform: Any CPU
clone_depth: 1
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
nuget:
  disable_publish_on_pr: true
before_build:
- cmd: dotnet restore Logzio.NLog.Extension.sln /p:Configuration=Release /p:Platform="Any CPU"
build:
  project: src\Logzio.NLog.Extensions\Logzio.NLog.Extension.csproj
  verbosity: minimal
test:
  assemblies:
    only:
    - tests\Logzio.NLog.Extensions.Tests\Logzio.NLog.Extensions.Tests.csproj
after_test:
- cmd: dotnet pack src\Logzio.NLog.Extensions\Logzio.NLog.Extensions.csproj
artifacts:
- path: '**\*.nupkg'
  name: LogzioNLogExtensions
deploy:
- provider: NuGet
  api_key:
    secure: pS/lyHg6LcDkR995HR5EUxEgF4W8124Zl6vmBZSJJurU/mPxPTSYms9wBXzNp5FP
  skip_symbols: false
  artifact: LogzioNLogExtensions
  on:
    branch: main